# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us, ch
    kb_variant = , fr
    kb_model =
    kb_options = caps:hyper,grp:shift_caps_toggle
    kb_rules =

    follow_mouse = 1

    numlock_by_default = true
}
bind = MOD3, SHIFT, exec, hyprctl switchxkblayout @all next

cursor {
    no_hardware_cursors = 0 # avoid weird issue with ghost cursor not disappearing
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = logitech-gaming-mouse-g502
    sensitivity = 2
    accel_profile = adaptive
}
