env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = QT_QPA_PLATFORMTHEME,hyprqt6engine


# load sub-confs
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/devices.conf
source = ~/.config/hypr/premissions.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/bindings.conf
