# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 2560x1440, 0x0, 1
monitor = HDMI-A-1, 2560x1440, 2560x0, 1

# Bind workspaces 1, 2, and 3 to DP-1
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1

# Bind workspaces 4, 5, and 6 to HDMI-A-1
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1