# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules


windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# floating windows
windowrule = match:class ^(floating-monitor)$, float on
windowrule = match:class ^(floating-monitor)$, size 1200 800

# Wofi app launcher
windowrule = match:class ^(wofi)$, float on
windowrule = match:class ^(wofi)$, center on
windowrule = match:class ^(wofi)$, stay_focused on
windowrule = match:class ^(wofi)$, pin on

# AltTab behavior
workspace = special:alttab, gapsout:0, gapsin:0, bordersize:0
windowrule = match:class alttab, no_anim on
windowrule = match:class alttab, stay_focused true
windowrule = match:class alttab, workspace special:alttab
windowrule = match:class alttab, border_size 0

# Steam games
windowrule {
    name = steam-games
    match:class = ^(steam_app_.*)$
    workspace = 2 silent

    immediate = true
    fullscreen = on
    fullscreen_state = 3
}
